# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# NOTE: Fix versions so everybody uses the same versions of all tools. Things become very messy otherwise.
#       It is OK to bump versions, but do it consiously. Run `pre-commit run --all-files` afterwards and
#       commit any updates.
exclude: |
    (?x)^(
      environment/cmake/.*\.patch|
      environment/cmake/UseLATEX\.cmake|
      environment/cmake/conan-.*\.cmake|
      source/view/imgui/include/lue/imgui/font/.*
    )$
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          # - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.1
      hooks:
          - id: mypy
            args: [--strict]
            # Skip game_of_life.py because a same-named script exists in quick_start ...
            exclude: |
                (?x)^(
                  source/data_model/python/test/.*|
                  document/doc/manual/quality_assurance/scalability/game_of_life.py|
                  document/luepy/ext/.*|
                  document/doc/manual/quality_assurance/scalability/game_of_life.py|
                  source/framework/case_study/.*|
                  source/framework/python/test/.*|
                  source/quality_assurance/scalability/.*|
                  source/quality_assurance/python/test/.*|
                )$
            additional_dependencies:
                - types-python-dateutil==2.9.0.20250809
    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.403
      hooks:
          - id: pyright
            exclude: |
                (?x)^(
                  source/data_model/python/test/.*|
                  document/doc/manual/quality_assurance/scalability/game_of_life.py|
                  document/luepy/ext/.*|
                  source/framework/case_study/.*|
                  source/framework/python/test/.*|
                  source/quality_assurance/scalability/.*|
                  source/quality_assurance/python/test/.*|
                )$
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.12.9
      hooks:
          # Run the linter.
          - id: ruff
          # Run the formatter.
          - id: ruff-format
    # TODO REQUIRES RUBY - repo: https://github.com/markdownlint/markdownlint
    # TODO REQUIRES RUBY   rev: v0.12.0
    # TODO REQUIRES RUBY   hooks:
    # TODO REQUIRES RUBY   - id: markdownlint
    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            additional_dependencies:
                - tomli
    - repo: https://github.com/crate-ci/typos
      rev: v1.35.4
      hooks:
          - id: typos
            args: [] # Relevant: don't update files, just report
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
          - id: clang-format
            args: [-i]
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5
      hooks:
          - id: clang-tidy
            args: [--quiet]
            # TODO Add directories not to be excluded
            exclude: |
                (?x)^(
                  source/.*|
                  source/data_model/cxx/.*|
                  source/data_model/gdal/include/lue/gdal/library.hpp|
                  source/data_model/hdf5/.*|
                  source/data_model/hl/.*|
                  source/data_model/python/.*|
                  source/data_model/test/.*|
                  source/data_model/translate/.*|
                  source/data_model/utility/.*|
                  source/data_model/validate/.*|
                  source/framework/.*|
                  source/view/.*|
                )$
